#!/usr/bin/env node
import {copyFile, mkdir, readdir, readFile, rm, stat, writeFile} from 'node:fs/promises';
import {dirname, extname, join, relative, resolve, sep} from 'node:path';
import * as prettier from 'prettier';

const INPUT_DIR = resolve('site');
const OUTPUT_DIR = resolve('readable', 'site');
const REPORT_PATH = resolve('readable', 'DEOPTIMIZE_REPORT.json');
const README_PATH = resolve('readable', 'README.md');

const parserByExtension = new Map([
  ['.css', 'css'],
  ['.js', 'babel'],
  ['.mjs', 'babel'],
  ['.json', 'json'],
  ['.webmanifest', 'json']
]);

const textExtensions = new Set(parserByExtension.keys());

async function walk(dir) {
  const entries = await readdir(dir, {withFileTypes: true});
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await walk(full));
    } else if (entry.isFile()) {
      files.push(full);
    }
  }
  return files;
}

function slashPath(pathname) {
  return pathname.split(sep).join('/');
}

async function formatText(source, parser, file) {
  const baseOptions = {
    parser,
    printWidth: 100,
    tabWidth: 2,
    singleQuote: true,
    bracketSameLine: false,
    htmlWhitespaceSensitivity: 'ignore'
  };

  try {
    return {
      text: await prettier.format(source, baseOptions),
      formatted: true,
      error: null
    };
  } catch (error) {
    return {
      text: source,
      formatted: false,
      error: `${file}: ${error.message}`
    };
  }
}

async function writeReadme(report) {
  const readme = `# Readable Tracing Art Mirror

This directory is generated by \`npm run deoptimize\`.

It is a full parallel copy of \`../site/\`:

- JS, CSS, JSON, and web manifest assets are formatted into readable files.
- SSR HTML, SVG, XML, and binary assets are copied byte-for-byte because
  whitespace can affect hydration-sensitive Nuxt output.
- Binary assets are copied byte-for-byte.
- The original scraped runtime in \`../site/\` is not modified.

The goal is to make the Nuxt bundle easier to inspect and gradually turn into a
maintainable source of truth later. The generated files are still compiled
runtime code, not recovered Vue source components.

## Serve The Readable Copy

\`\`\`bash
SITE_DIR=readable/site PORT=5175 npm run serve
\`\`\`

Then verify with:

\`\`\`bash
TARGET_URL=http://localhost:5175/tracingart/ npm run verify:puppeteer
TARGET_URL=http://localhost:5175/tracingart/ npm run verify:mobile
\`\`\`

## Last Generation

- Files copied: ${report.filesCopied}
- Text files formatted: ${report.textFormatted}
- Text files copied without formatting: ${report.textUnformatted}
- Binary files copied: ${report.binaryCopied}
- Formatting errors: ${report.errors.length}
`;

  await writeFile(README_PATH, readme);
}

async function main() {
  await stat(INPUT_DIR);
  await rm(resolve('readable'), {recursive: true, force: true});
  await mkdir(OUTPUT_DIR, {recursive: true});

  const report = {
    inputDir: INPUT_DIR,
    outputDir: OUTPUT_DIR,
    filesCopied: 0,
    textFormatted: 0,
    textUnformatted: 0,
    binaryCopied: 0,
    errors: []
  };

  const files = await walk(INPUT_DIR);
  for (const sourceFile of files) {
    const rel = slashPath(relative(INPUT_DIR, sourceFile));
    const targetFile = join(OUTPUT_DIR, rel);
    const ext = extname(sourceFile).toLowerCase();
    await mkdir(dirname(targetFile), {recursive: true});

    if (!textExtensions.has(ext)) {
      await copyFile(sourceFile, targetFile);
      report.binaryCopied++;
      report.filesCopied++;
      continue;
    }

    const source = await readFile(sourceFile, 'utf8');
    const result = await formatText(source, parserByExtension.get(ext), rel);
    await writeFile(targetFile, result.text);
    if (result.formatted) {
      report.textFormatted++;
    } else {
      report.textUnformatted++;
      report.errors.push(result.error);
    }
    report.filesCopied++;
  }

  await mkdir(dirname(REPORT_PATH), {recursive: true});
  await writeFile(REPORT_PATH, JSON.stringify(report, null, 2));
  await writeReadme(report);

  console.log(JSON.stringify(report, null, 2));
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
